# Cloudflare Pages 配置文件
name = "environment-management-system"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment_variables]
NODE_VERSION = "18"

# Pages 特定配置
pages_build_output_dir = "dist"
