name = "environment-manager"
main = "src/worker.js"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "ENV_CONFIG"
id = "4a3aeaec065946a4a23f9c249537def3"
preview_id = "4a3aeaec065946a4a23f9c249537def3"

# 环境变量配置
[vars]
# 版本控制 - 更新版本号会强制刷新缓存
APP_VERSION = "2.1.0"
BUILD_TIME = "2025-01-15T18:30:00Z"
ENVIRONMENT = "production"

# 缓存控制
CACHE_BUST_ENABLED = "true"      # 启用缓存破坏
FORCE_REFRESH = "false"          # 强制刷新开关

# 缓存配置（秒）- 可根据需要调整
CACHE_STATIC_ASSETS = "604800"   # 7天（您之前设置的值）
CACHE_API_RESPONSES = "300"      # 5分钟（您之前设置的值）
CACHE_HEALTH_CHECK = "60"        # 1分钟（您之前设置的值）
CACHE_KV_CACHE = "36000"         # 1小时（您之前设置的值）

# 敏感环境变量在 Cloudflare Dashboard 中配置:
# - JWT_SECRET