name = "environment-manager"
main = "src/worker.js"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# 所有敏感配置已在 Cloudflare Dashboard 中配置:
# - KV 绑定: ENV_CONFIG → demo-workers
# - 环境变量: JWT_SECRET 等

workers_dev = true

